import { useEffect, useState } from 'react';

const api = async (url, options = {}) => {
  const r = await fetch(url, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options });
  const data = await r.json().catch(() => ({}));
  if (!r.ok) throw new Error(data.error || 'Erro na operação.');
  return data;
};

function Login({ onLogin }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async e => { e.preventDefault(); setBusy(true); setError(''); try { const d = await api('/api/auth/login', { method:'POST', body:JSON.stringify({email,password}) }); onLogin(d.user); } catch (x) { setError(x.message); } finally { setBusy(false); } };
  return <main className="login"><form className="login-card" onSubmit={submit}><div className="brand">Mini<span>Lix</span></div><p className="muted">Gestão de coleta de resíduos</p><h1>Acessar plataforma</h1>{error && <div className="alert">{error}</div>}<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required /></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required /></label><button disabled={busy}>{busy?'Entrando…':'Entrar'}</button></form></main>;
}

function App() {
  const [user,setUser]=useState(null), [view,setView]=useState('dashboard'), [stats,setStats]=useState(null), [customers,setCustomers]=useState([]), [containers,setContainers]=useState([]), [orders,setOrders]=useState([]), [drivers,setDrivers]=useState([]), [error,setError]=useState('');
  const load = async () => { try { const [me,st,cs,ct,os] = await Promise.all([api('/api/auth/me'),api('/api/dashboard'),api('/api/customers'),api('/api/containers'),api('/api/orders')]); setUser(me.user);setStats(st);setCustomers(cs);setContainers(ct);setOrders(os); if(me.user.role!=='MOTORISTA') setDrivers(await api('/api/drivers')); } catch { setUser(null); } };
  useEffect(()=>{load()},[]);
  if(!user) return <Login onLogin={u=>{setUser(u);load()}}/>;
  const logout=async()=>{await api('/api/auth/logout',{method:'POST'});setUser(null)};
  const refresh=async()=>{const [st,cs,os]=await Promise.all([api('/api/dashboard'),api('/api/customers'),api('/api/orders')]);setStats(st);setCustomers(cs);setOrders(os)};
  return <div className="app"><aside><div className="brand">Mini<span>Lix</span></div><div className="role">{user.name}<small>{user.role}</small></div><nav>{[['dashboard','Dashboard'],['customers','Clientes'],['rental','Nova Locação'],['orders','Ordens de Serviço'],['driver','Tela do Motorista']].map(([k,l])=><button className={view===k?'active':''} onClick={()=>setView(k)} key={k}>{l}</button>)}</nav><button className="logout" onClick={logout}>Sair</button></aside><main className="content"><header><div><div className="eyebrow">OPERAÇÃO MINILIX</div><h1>{({dashboard:'Visão geral',customers:'Clientes',rental:'Nova Locação',orders:'Ordens de Serviço',driver:'Tela do Motorista'})[view]}</h1></div><div className="user-pill">{user.name}</div></header>{error&&<div className="alert">{error}</div>}{view==='dashboard'&&<Dashboard stats={stats}/>} {view==='customers'&&<Customers customers={customers} onCreated={refresh}/>} {view==='rental'&&<Rental customers={customers} containers={containers} onCreated={async()=>{await refresh();setView('orders')}}/>} {view==='orders'&&<Orders orders={orders} drivers={drivers} user={user} onRefresh={refresh}/>} {view==='driver'&&<Driver user={user} onRefresh={refresh}/>}</main></div>;
}

const Dashboard=({stats})=><section><div className="cards">{[['Clientes',stats?.customers??0],['OS abertas',stats?.openOrders??0],['OS hoje',stats?.todayOrders??0],['Pendentes',stats?.pendingOrders??0]].map(x=><div className="card" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div><div className="panel"><h2>Fluxo operacional</h2><p>Cadastre o cliente → crie a locação → a OS é gerada automaticamente → atribua ao motorista → acompanhe a execução.</p></div></section>;

function Customers({customers,onCreated}){const [form,setForm]=useState({name:'',document:'',phone:'',email:''}); const [msg,setMsg]=useState(''); const save=async e=>{e.preventDefault();try{await api('/api/customers',{method:'POST',body:JSON.stringify(form)});setForm({name:'',document:'',phone:'',email:''});setMsg('Cliente cadastrado.');onCreated()}catch(x){setMsg(x.message)}};return <section className="grid2"><form className="panel" onSubmit={save}><h2>Novo cliente</h2>{msg&&<div className="notice">{msg}</div>}<label>Nome / Razão social<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>CPF/CNPJ<input value={form.document} onChange={e=>setForm({...form,document:e.target.value})}/></label><label>Telefone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>E-mail<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><button>Cadastrar cliente</button></form><div className="panel"><h2>Clientes cadastrados</h2><div className="table">{customers.map(c=><div className="row" key={c.id}><b>{c.name}</b><span>{c.phone||'—'}</span></div>)}</div></div></section>}

function Rental({customers,containers,onCreated}){const [f,setF]=useState({customerId:'',scheduledDate:new Date().toISOString().slice(0,10),containerId:'',quantity:1,street:'',number:'',neighborhood:'',city:'Sorocaba',state:'SP',cep:'',reference:'',notes:''});const [msg,setMsg]=useState('');const set=(k,v)=>setF(x=>({...x,[k]:v}));const save=async e=>{e.preventDefault();try{const d=await api('/api/rentals',{method:'POST',body:JSON.stringify({customerId:f.customerId,scheduledDate:f.scheduledDate,containerId:f.containerId,quantity:Number(f.quantity),notes:f.notes,address:{street:f.street,number:f.number,neighborhood:f.neighborhood,city:f.city,state:f.state,cep:f.cep,reference:f.reference}})});setMsg(`Locação criada. ${d.number}`);onCreated()}catch(x){setMsg(x.message)}};return <form className="panel" onSubmit={save}><h2>Nova Locação</h2>{msg&&<div className="notice">{msg}</div>}<div className="formgrid"><label>Cliente<select value={f.customerId} onChange={e=>set('customerId',e.target.value)} required><option value="">Selecione…</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Data<select value={f.scheduledDate} onChange={e=>set('scheduledDate',e.target.value)}><option value={f.scheduledDate}>{f.scheduledDate}</option></select></label><label>Recipiente<select value={f.containerId} onChange={e=>set('containerId',e.target.value)} required><option value="">Selecione…</option>{containers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Quantidade<input type="number" min="1" value={f.quantity} onChange={e=>set('quantity',e.target.value)}/></label></div><h3>Endereço da coleta</h3><div className="formgrid"><label>CEP<input value={f.cep} onChange={e=>set('cep',e.target.value)}/></label><label>Rua / Avenida<input value={f.street} onChange={e=>set('street',e.target.value)} required/></label><label>Número<input value={f.number} onChange={e=>set('number',e.target.value)} required/></label><label>Bairro<input value={f.neighborhood} onChange={e=>set('neighborhood',e.target.value)}/></label><label>Cidade<input value={f.city} onChange={e=>set('city',e.target.value)} required/></label><label>UF<input value={f.state} onChange={e=>set('state',e.target.value)} maxLength="2"/></label></div><label>Referência<input value={f.reference} onChange={e=>set('reference',e.target.value)}/></label><label>Observações<textarea value={f.notes} onChange={e=>set('notes',e.target.value)}/></label><button>Gerar Locação + OS</button></form>}

function Orders({orders,drivers,user,onRefresh}){const assign=async(id,driverId)=>{await api(`/api/orders/${id}/driver`,{method:'PATCH',body:JSON.stringify({driverId})});onRefresh()};const status=async(id,s)=>{await api(`/api/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status:s})});onRefresh()};return <div className="panel"><div className="panelhead"><h2>Ordens de Serviço</h2><button className="secondary" onClick={onRefresh}>Atualizar</button></div><div className="table">{orders.map(o=><div className="order" key={o.id}><div><b>{o.number}</b><span>{o.customer_name} · {o.street}, {o.number} · {o.scheduled_date}</span></div><div className="actions"><span className="badge">{o.status}</span>{user.role!=='MOTORISTA'&&<select value={o.driver_id||''} onChange={e=>assign(o.id,e.target.value)}><option value="">Motorista…</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select>}<select value="" onChange={e=>status(o.id,e.target.value)}><option value="">Status…</option><option value="A_CAMINHO">A caminho</option><option value="NO_LOCAL">No local</option><option value="CONCLUIDA">Concluída</option><option value="CANCELADA">Cancelada</option></select></div></div>)}</div></div>}

function Driver({user,onRefresh}){const [items,setItems]=useState([]);useEffect(()=>{api('/api/driver/orders').then(setItems).catch(()=>{})},[onRefresh]);const status=async(id,s)=>{await api(`/api/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status:s})});setItems(await api('/api/driver/orders'));onRefresh()};return <div className="cardscol">{items.length===0&&<div className="panel">Nenhuma OS atribuída a {user.name}.</div>}{items.map(o=><div className="panel driver-card" key={o.id}><div><span className="badge">{o.status}</span><h2>{o.number}</h2><b>{o.customer_name}</b><p>{o.street}, {o.number} — {o.neighborhood}, {o.city}</p><p>{o.phone||''}</p></div><div className="driver-actions"><button onClick={()=>status(o.id,'A_CAMINHO')}>A caminho</button><button onClick={()=>status(o.id,'NO_LOCAL')}>No local</button><button onClick={()=>status(o.id,'CONCLUIDA')}>Concluir</button></div></div>)}</div>}

export default App;
