import {useEffect,useState} from 'react';
const api=async(url,options={})=>{const r=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Erro na operação.');return d};
const statusLabel={DISPONIVEL:'Disponível',ALUGADO:'Alugado',MANUTENCAO:'Manutenção',INATIVO:'Inativo'};
export default function V5Assets(){
 const[open,setOpen]=useState(false),[items,setItems]=useState([]),[selected,setSelected]=useState(null),[history,setHistory]=useState([]),[qr,setQr]=useState(null),[loading,setLoading]=useState(false),[err,setErr]=useState('');
 const load=async()=>{setLoading(true);setErr('');try{setItems(await api('/api/assets'))}catch(e){setErr(e.message)}finally{setLoading(false)}};
 useEffect(()=>{if(open)load()},[open]);
 const detail=async a=>{setSelected(a);setQr(null);setErr('');try{setHistory(await api(`/api/assets/${a.id}/history`))}catch(e){setErr(e.message)}};
 const change=async(status)=>{if(!selected)return;try{await api(`/api/assets/${selected.id}`,{method:'PATCH',body:JSON.stringify({status})});await load();const fresh=(await api('/api/assets')).find(x=>x.id===selected.id);if(fresh)await detail(fresh)}catch(e){setErr(e.message)}};
 const showQr=async()=>{try{setQr(await api(`/api/assets/${selected.id}/qr`))}catch(e){setErr(e.message)}};
 const counts=items.reduce((x,a)=>(x[a.status]=(x[a.status]||0)+1,x),{});
 return <>
  <button onClick={()=>setOpen(v=>!v)} style={{position:'fixed',right:22,bottom:78,zIndex:9997,border:0,borderRadius:999,padding:'11px 16px',fontWeight:800,cursor:'pointer',boxShadow:'0 8px 24px rgba(0,0,0,.15)'}}>V5 · Patrimônio</button>
  {open&&<div style={{position:'fixed',right:22,bottom:136,zIndex:9996,width:'min(560px,calc(100vw - 32px))',maxHeight:'calc(100vh - 170px)',overflow:'auto',background:'#fff',borderRadius:18,boxShadow:'0 18px 55px rgba(0,0,0,.22)',padding:20,border:'1px solid #e5e7eb'}}>
   <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:12,fontWeight:800,letterSpacing:1}}>MINILIX · V5.3</div><h2 style={{margin:'4px 0'}}>Central patrimonial</h2></div><button onClick={load} disabled={loading}>{loading?'…':'Atualizar'}</button></div>
   {err&&<div style={{marginTop:12,padding:10,borderRadius:10,background:'#fff1f2'}}>{err}</div>}
   <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:8,marginTop:14}}>{[['Disponíveis','DISPONIVEL'],['Alugados','ALUGADO'],['Manutenção','MANUTENCAO'],['Inativos','INATIVO']].map(([l,s])=><div key={s} style={{padding:10,borderRadius:10,background:'#f8fafc',textAlign:'center'}}><small>{l}</small><strong style={{display:'block',fontSize:20}}>{counts[s]||0}</strong></div>)}</div>
   <div style={{marginTop:16,display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(155px,1fr))',gap:8}}>{items.map(a=><button key={a.id} onClick={()=>detail(a)} style={{textAlign:'left',padding:12,borderRadius:12,border:selected?.id===a.id?'2px solid #111':'1px solid #e5e7eb',background:'#fff',cursor:'pointer'}}><b>{a.patrimony_code}</b><div style={{fontSize:12,color:'#64748b'}}>{a.name}</div><div style={{marginTop:5,fontSize:12}}>{statusLabel[a.status]||a.status}</div></button>)}</div>
   {selected&&<div style={{marginTop:16,padding:14,borderRadius:12,background:'#f8fafc'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><h3 style={{margin:'0 0 4px'}}>{selected.patrimony_code}</h3><div>{selected.name} · {selected.capacity_liters} L</div><div style={{fontSize:13,color:'#64748b'}}>QR: {selected.qr_token}</div></div><button onClick={showQr}>Gerar QR Code</button></div><div style={{marginTop:10}}><label style={{fontSize:13}}>Alterar situação<select value={selected.status} onChange={e=>change(e.target.value)} style={{marginLeft:8}}>{Object.entries(statusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div>{qr&&<div style={{marginTop:12,textAlign:'center'}}><img src={qr.qrUrl} alt={`QR ${selected.patrimony_code}`} width="180" height="180"/><div style={{fontSize:12}}>Identificação patrimonial MiniLix</div></div>}<h4 style={{margin:'16px 0 8px'}}>Histórico</h4>{history.length===0?<div style={{fontSize:13,color:'#64748b'}}>Nenhum evento registrado.</div>:history.slice(0,12).map(e=><div key={e.id} style={{padding:'8px 0',borderBottom:'1px solid #e5e7eb',fontSize:13}}><b>{e.event_type}</b> · {e.description||'—'}<div style={{color:'#64748b'}}>{e.customer_name||'Sem cliente'} · {e.user_name||'Sistema'} · {e.created_at?new Date(e.created_at).toLocaleString('pt-BR'):''}</div></div>)}</div>}
  </div>}
 </>;
}
