import {useEffect,useMemo,useState} from 'react';

const api=async(url,options={})=>{const r=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Não foi possível concluir a operação.');return d};
const money=n=>`R$ ${Number(n||0).toFixed(2).replace('.',',')}`;

export default function V61Clients(){
 const[user,setUser]=useState(null),[customers,setCustomers]=useState([]),[units,setUnits]=useState([]),[q,setQ]=useState(''),[selected,setSelected]=useState(null),[rentals,setRentals]=useState([]),[open,setOpen]=useState(false),[newOpen,setNewOpen]=useState(false),[loading,setLoading]=useState(false),[err,setErr]=useState(''),[form,setForm]=useState({name:'',document:'',phone:'',email:'',notes:''});
 const load=async()=>{setLoading(true);setErr('');try{const m=await api('/api/auth/me');setUser(m.user);if(m.user.role==='ADMIN'||m.user.role==='ATENDIMENTO'){const [cs,us,rs]=await Promise.all([api('/api/customers'),api('/api/units'),api('/api/rentals')]);setCustomers(cs);setUnits(us);setRentals(rs)}}catch(e){setErr(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>customers.filter(c=>`${c.name} ${c.document||''} ${c.phone||''} ${c.email||''}`.toLowerCase().includes(q.toLowerCase())).slice(0,50),[customers,q]);
 const unit=units[0];
 const mine=selected?rentals.filter(r=>r.customer_id===selected.id):[];
 const save=async e=>{e.preventDefault();setErr('');try{await api('/api/customers',{method:'POST',body:JSON.stringify(form)});setForm({name:'',document:'',phone:'',email:'',notes:''});setNewOpen(false);await load()}catch(e){setErr(e.message)}};
 if(!user||!['ADMIN','ATENDIMENTO'].includes(user.role))return null;
 return <><button className="v5-fab v6-clients-fab" onClick={()=>setOpen(true)}>👥 Clientes V6</button>{open&&<div className="v5-overlay"><section className="v5-panel">
 <div className="v5-panel-head"><div><span className="v5-kicker">V6.1 • CLIENTES</span><h2>Central de Clientes</h2><p>Cadastro, histórico e vínculo operacional por unidade.</p></div><button onClick={()=>setOpen(false)}>Fechar</button></div>
 {err&&<div className="client-alert">{err}</div>}
 <div className="v5-cards"><div className="v5-card"><b>👥 {customers.length}</b><span>Clientes cadastrados</span></div><div className="v5-card"><b>🏢 {unit?.name||'Sorocaba'}</b><span>Unidade de atendimento</span></div><div className="v5-card"><b>📦 {rentals.length}</b><span>Locações registradas</span></div></div>
 <div style={{display:'flex',gap:10,marginTop:14,flexWrap:'wrap'}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar nome, documento, telefone ou e-mail" style={{flex:1,minWidth:240}}/><button className="primary" onClick={()=>setNewOpen(v=>!v)}>+ Novo cliente</button><button onClick={load} disabled={loading}>{loading?'Atualizando…':'Atualizar'}</button></div>
 {newOpen&&<form onSubmit={save} style={{display:'grid',gap:10,marginTop:14,padding:14,background:'#f8fafc',borderRadius:14}}><strong>Novo cliente</strong><div className="v5-cards"><label>Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Documento<input value={form.document} onChange={e=>setForm({...form,document:e.target.value})}/></label><label>Telefone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label></div><label>Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary">Salvar cliente</button></form>}
 <div style={{display:'grid',gridTemplateColumns:'minmax(220px,.8fr) 1.2fr',gap:14,marginTop:14}}>
 <div>{filtered.map(c=><button key={c.id} onClick={()=>setSelected(c)} style={{display:'block',width:'100%',textAlign:'left',padding:12,marginBottom:7,border:'1px solid #e5e7eb',borderRadius:10,background:selected?.id===c.id?'#e8f5ed':'#fff',cursor:'pointer'}}><b>{c.name}</b><div style={{fontSize:12,color:'#64748b'}}>{c.phone||c.email||'Sem contato'}</div></button>)}{!filtered.length&&<p>Nenhum cliente encontrado.</p>}</div>
 <div>{!selected?<div className="v5-card"><b>Selecione um cliente</b><span>Veja locações, endereço, quantidade de tambores e situação operacional.</span></div>:<><div className="v5-card"><b>{selected.name}</b><span>{selected.document||'Sem documento'} · {selected.phone||'Sem telefone'}</span><span>{selected.email||'Sem e-mail'}</span><span>Unidade: {unit?.name||'MiniLix Sorocaba'}</span></div><h3 style={{margin:'16px 0 8px'}}>Histórico de locações</h3>{mine.length?mine.map(r=><div key={r.id} className="v5-card" style={{marginBottom:8}}><b>{r.scheduled_date?.slice(0,10)?.split('-').reverse().join('/')||'—'} · {r.status}</b><span>{r.street}, {r.number} · {r.city}</span><span>{r.container_quantity||0} tambor(es) · vencimento {r.due_date?.slice(0,10)?.split('-').reverse().join('/')||'—'}</span></div>):<p>Nenhuma locação encontrada para este cliente.</p>}</>}</div></div>
 <div style={{marginTop:14,padding:12,borderRadius:10,background:'#f0fdf4',fontSize:12,color:'#166534'}}>V6.1 prepara o cadastro para múltiplas unidades sem alterar os registros existentes.</div>
 </section></div>}</>
}