import {useEffect,useState} from 'react';

const api=async(url,options={})=>{const r=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Não foi possível concluir a operação.');return d};

export default function V6Units(){
  const[user,setUser]=useState(null),[units,setUnits]=useState([]),[form,setForm]=useState({name:'',code:'',city:'',state:'SP',type:'PROPRIA'}),[open,setOpen]=useState(false),[err,setErr]=useState('');
  const load=async()=>{try{const m=await api('/api/auth/me');setUser(m.user);if(m.user.role==='ADMIN')setUnits(await api('/api/units'))}catch{}};
  useEffect(()=>{load()},[]);
  if(!user||user.role!=='ADMIN')return null;
  const save=async e=>{e.preventDefault();setErr('');try{await api('/api/units',{method:'POST',body:JSON.stringify(form)});setForm({name:'',code:'',city:'',state:'SP',type:'PROPRIA'});setOpen(false);await load()}catch(x){setErr(x.message)}};
  return <><button className="v5-fab v6-units-fab" onClick={()=>setOpen(true)}>🏢 Unidades</button>{open&&<div className="v5-overlay"><section className="v5-panel"><div className="v5-panel-head"><div><span className="v5-kicker">V6 • EXPANSÃO</span><h2>Unidades MiniLix</h2><p>Base preparada para múltiplas unidades e franquias.</p></div><button onClick={()=>setOpen(false)}>Fechar</button></div>{err&&<div className="client-alert">{err}</div>}<div className="v5-cards">{units.map(u=><div className="v5-card" key={u.id}><b>🏢 {u.name}</b><span>Código: {u.code}</span><span>{u.city||'Cidade não definida'} / {u.state||'SP'}</span><span>{u.type==='FRANQUIA'?'Franquia':'Unidade própria'} · {u.active?'Ativa':'Inativa'}</span></div>)}</div><button onClick={()=>setOpen(!false)} style={{marginTop:16}} className="primary">+ Nova unidade</button><form onSubmit={save} style={{display:'grid',gap:10,marginTop:12}}><label>Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Código<input value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})} required/></label><div className="v5-cards"><label>Cidade<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>UF<input value={form.state} onChange={e=>setForm({...form,state:e.target.value.toUpperCase()})} maxLength="2"/></label><label>Tipo<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="PROPRIA">Própria</option><option value="FRANQUIA">Franquia</option></select></label></div><button className="primary">Salvar unidade</button></form></section></div>}</>
}
